### ISSUE TITLE
The connection string isn't parsed correctly in Windows PowerShell

### ISSUE THREAD

**Issue by ianjevans** [cockroachlabs/example-app-node-postgres#3]
From Richard C. on Slack:
> the connection string isn't parsed correctly in windows
> 
> ```
> const command = `cockroach sql --url '${connectionString}' < dbinit.sql`;
> ```
> 
> If you copy in a windows path for your input from the prompt, the slashes don't parse correctly.
> Also most windows users I encountered use powershell and theres no redirection operator.

This caused problems during a Hackathon event.

I think we could replace the redirect with `--file dbinit.sql`.

**Comment by ericharmeling** [comment]
Thanks for filing this. 

Does `--file dbinit.sql` resolve the issue on Windows?

One drawback to using `--file`/`-f` is that these flags are not supported in CRDB versions < 21.1. (I don't believe https://github.com/cockroachdb/cockroach/pull/54741 was backported).

**Comment by ianjevans** [comment]
There are two separate issues keeping this from working on Windows:

1. The slashes in the connection string aren't parsed correctly on Windows.
2. The `cockroachdb sql` command doesn't work with Unix-style redirection on Windows.

> One drawback to using `--file/-f` is that these flags are not supported in CRDB versions < 21.1. (I don't believe cockroachdb/cockroach#54741 was backported).

The CC console gives instructions on downloading v21.1 binaries for Windows:
<img width="750" alt="Screen Shot 2021-08-23 at 9 18 53 AM" src="https://user-images.githubusercontent.com/5760366/130482191-7553a376-18f4-4a33-ac2d-b7458f0315e2.png">

So presumably Windows users would be able to connect to < v21.1 clusters if they are using v21.1+ binaries, yeah?

**Comment by ericharmeling** [comment]
I'm just going to remove the `command` const and have users run the `cockroach` command themselves. That should resolve both of these issues.

The remaining problem is that the environment variable is not `$HOME` in Windows connection strings. (As you pointed out here: https://github.com/cockroachlabs/hello-world-node-postgres/issues/1). I can resolve that by just adding an extra condition on the connection string.
